# Generated by Django 4.0.6 on 2022-07-26 14:42

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sectionlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sectionlist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='0810000000', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='profile_pictures'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('shortnote', models.CharField(max_length=150)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(default='document.png', upload_to='document_image')),
                ('uploadfile', models.FileField(upload_to='document_file', verbose_name='Document')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.sectionlist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.sectionlist'),
        ),
    ]
