# Generated by Django 4.0.6 on 2022-07-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sectionlist_document_alter_profile_sectionlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sectionlist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='0812345678', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures'),
        ),
    ]
