# Generated by Django 4.0.6 on 2022-07-15 10:46

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='media',
        ),
        migrations.AddField(
            model_name='document',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.sectionlist'),
        ),
        migrations.AddField(
            model_name='document',
            name='shortnote',
            field=models.TextField(default='รายละเอียดตัวชี้วัด'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='0812345678', max_length=20),
        ),
    ]
