# Generated by Django 4.0.6 on 2022-07-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_document_content_alter_document_shortnote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploadfile',
            field=models.FileField(upload_to='document_file', verbose_name='Document'),
        ),
    ]
