# Generated by Django 4.0.6 on 2022-07-15 12:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_document_media_document_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(default='document.png', upload_to='document_image'),
        ),
        migrations.AlterField(
            model_name='document',
            name='shortnote',
            field=models.CharField(default='คำอธิบายอย่างย่อ', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='0810000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='profile_pictures'),
        ),
    ]
